[package]
name = "genie-hki"
version = "0.2.1"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"
license = "GPL-3.0"
description = "Read Age of Empires I/II hotkey files."
homepage = "https://github.com/SiegeEngineers/genie-rs"
repository = "https://github.com/SiegeEngineers/genie-rs"
exclude = ["test/files"]

[dependencies]
byteorder = "1.3.4"
flate2 = "1.0.18"
genie-lang = { version = "^0.2.0", path = "../genie-lang" }
thiserror = "1.0.21"

[dev-dependencies]
anyhow = "1.0.33"
