[package]
name = "genie-drs"
version = "0.2.0"
authors = ["Ren√©e Kooi <renee@kooi.me>"]
edition = "2018"
license = "GPL-3.0"
description = "Read .drs archive files from the Genie Engine, used in Age of Empires 1/2 and SWGB"
homepage = "https://github.com/SiegeEngineers/genie-rs"
repository = "https://github.com/SiegeEngineers/genie-rs"
readme = "README.md"
exclude = ["*.drs"]

[dependencies]
byteorder = "^1.3.1"
sorted-vec = "^0.3.0"
